server:
  port: 9500
  servlet:
    context-path: /xxx-ms

spring:
  application:
    name: xxx-ms
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:dao/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_


cache:
  #是否启用缓存
  enable: true
  #key前缀
  key-prefix: xxx
