server:
  port: 9500
  servlet:
    context-path: /xxx-ms

spring:
  application:
    name: xxx-ms
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:dao/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_

pagehelper:
  helper-dialect: mysql

knife4j:
  #是否启用增强配置
  enable: true
  #生产环境是否屏蔽接口文档
  production: true

cache:
  #是否启用缓存
  enable: true
  #key前缀
  key-prefix: xxx

security:
  #白名单url，直接放行
  ignore-urls:
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /**/*.png
    - /**/*.jpg
    - /**/*.gif
    - /**/*.webp
    - /**/*.ico
    - /swagger-resources/**
    - /v2/api-docs
    - /v2/api-docs-ext
    - /actuator/**
    - /v1/system/users/login

jwt.token:
  #传递token的请求头字段
  request-header: Authorization
  #token前缀
  prefix: 'Bearer '
  #token加解密使用的密钥
  secret: xxx-ms-secret
  #token有效期，单位：秒
  expiration: 3600
  #在token过期前多久秒内可以刷新token，单位：秒
  refresh-before-expire: 1200
  #通知前端刷新token的响应头字段
  refresh-response-header: Refresh-Token

system:
  user:
    #添加新用户、重置密码时设置的默认密码，至少4个字符
    default-password: 1234
