spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxx-ms?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abcd

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
